### ISSUE TITLE
error API berita detik

### ISSUE THREAD

**Issue by Muqoffin** [renomureza/api-berita-indonesia#2]
Hi kak, ini kenapa ya kak saat dibagian berita detik?
![Screenshot_select-area_20210707163844](https://user-images.githubusercontent.com/61044238/124750977-4f8dc180-df50-11eb-8129-628921a6c8e1.png)

**Comment by renomureza** [comment]
Hi @Muqoffin , 

Detik sudah dihapus karena data RSS tidak lengkap.

Beberapa data awalnya diambil dari HTML halaman masing-masing berita, butuh waktu yang lumayan lama untuk mendapatkan data utuh sehingga menyebabkan error seperti di screenshoot karena waktu eksekusi server Vercel di batasi: https://vercel.com/docs/error/application/FUNCTION_INVOCATION_TIMEOUT
